apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: {{ include "helm-charts.name" . }}
    chart: {{ include "helm-charts.name" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ include "helm-charts.name" . }}-hpa
spec:
  scaleTargetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ include "helm-charts.name" . }}
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
