kind: Service
apiVersion: v1
metadata:
  name: {{ include "helm-charts.name" . }}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
      nodePort: 30081
  selector:
    app: {{ include "helm-charts.name" . }}